config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'store#index', as: 'store'

  resources :products, except: :index
  resources :line_items, only: [:create, :destroy]
  resources :carts, only: [:show]
  resources :orders, except: [:edit, :update]

  # session
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy', as: :logout

end

app/models/cart.rb
# == Schema Information
#
# Table name: carts
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Cart < ActiveRecord::Base

  has_many :line_items, dependent: :destroy
  has_one :order

  def add_product(product_id)
    current_line_item = line_items.find_by product_id: product_id
    current_line_item = line_items.build(product_id: product_id) if current_line_item.nil?
    current_line_item.quantity += 1
    current_line_item.save!
  end

  def count_products_in_cart
    line_items.sum(:quantity)
  end

  def has_line_item?(line_item)
    line_items.include? line_item
  end

  def remove_product_from_line_item(line_item)
    if line_item.quantity > 1
      line_item.quantity -= 1
      line_item.save!
    else
      line_item.destroy
    end
  end

# for another way of destroying

=begin
if has_line_item?(line_item)
  if line_item.quantity > 1
      line_item.quantity -= 1
      line_item.save!
  else
     line_item.destroy!
  end
  'Item removed from the cart'
else
  'It\'s not your cart'
end
=end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :destroy]
  skip_before_action :authorize, only: [:show, :destroy]

  # GET /carts/1
  def show
    if @cart.id != session[:cart_id]
      redirect_to store_path, notice: 'It\'s not your cart'
    end
  end

  # DELETE /carts/1
  def destroy
    @cart.destroy
  end

  private
  def set_cart
    @cart = Cart.find(params[:id])
  end
end

app/helpers/carts_helper.rb
module CartsHelper

  def total_price(cart)
    price = 0
    cart.line_items.each do |line_item|
      price += line_item.quantity * line_item.product.price
    end
    price
  end

  def minus_label
    '<span class="glyphicon glyphicon-minus" aria-hidden="true"></span>'.html_safe
  end

  def plus_label
    '<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>'.html_safe
  end
end

app/views/carts/show.html.erb
<% if notice %>
    <div class="alert alert-success" role="alert">
      <p id="notice"><%= notice %></p>
    </div>
<% end %>

<div class="col-md-3"></div>
<div class="col-md-5">
  <table class="table">
    <thead>
        <tr>
          <th class="cell">Title</th>
          <th class="cell">Quantity</th>
          <th class="cell">Price</th>
          <th class="cell">Actions</th>
        </tr>
    </thead>
    <tbody>
    <% @cart.line_items.each do |line_item| %>
        <tr>
          <th scope="row"  class="cell"><%= line_item.product.title %></th>
          <th class="cell"><%= line_item.quantity %></th>
          <th class="cell"><%= number_to_currency line_item.product.price %></th>
          <th class="cell">
            <%= link_to plus_label, line_items_path(product_id: line_item.product), method: :post %>
            <%= link_to minus_label, line_item, method: :delete, data: {confirm: 'Are you sure?'} %>
          </th>
        </tr>
    <% end %>
    </tbody>
  </table>
  <p class="total_price">Total price: <%= number_to_currency total_price(@cart) %></p>
  <hr>
  <p class="order"><%= link_to 'Make an order', new_order_path, class: 'make_order' unless @cart.line_items.empty? %></p>
</div>