config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'store#index', as: 'store'

  resources :products, except: :index
  resources :line_items, only: [:create, :destroy]
  resources :carts, only: [:show]
  resources :orders, except: [:edit, :update]

  # session
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy', as: :logout

end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  image_url   :string
#  price       :decimal(8, 2)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Product < ActiveRecord::Base

  validates :title, :description, :image_url, :price, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  validates :title, uniqueness: true
  validates :image_url, format: {
                with: %r{\.(jpg|png|gif)}i,
                message: 'URL should include jpg, png or gif'
                      }

  paginates_per 12
  has_many :line_items

  before_destroy :check_line_items_on_product

  private
  def check_line_items_on_product
    line_items.empty?
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize, only: :show

  # GET /products/1
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /products/1
  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /products/1
  def destroy
    @product.destroy
    redirect_to products_url, notice: 'Product was successfully destroyed.'
  end

  private
  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:title, :description, :image_url, :price)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= bootstrap_form_for(@product) do |f| %>

  <div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6">
  <div class="field">
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.text_area :description, class: 'form-control', rows: '5' %>
  </div>
  <div class="field">
    <%= f.text_field :image_url, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.text_field :price, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
  </div>
    <div class="col-md-3"></div>
  </div>
<% end %>

app/views/products/edit.html.erb
<div class="page-header">
  <h1>Editing Product</h1>
</div>

<% if notice %>
    <div class="alert alert-success" role="alert">
      <p id="notice"><%= notice %></p>
    </div>
<% end %>

<%= render 'form' %>

<div class="col-md-11"></div>
<div class="col-md-1">
    <%= link_to 'Show', @product %> |
    <%= link_to 'Back', store_path %>
</div>

app/views/products/new.html.erb
<div class="page-header">
  <h1>New Product</h1>
</div>

<% if notice %>
    <div class="alert alert-success" role="alert">
      <p id="notice"><%= notice %></p>
    </div>
<% end %>

<%= render 'form' %>

<div class="col-md-11"></div>
<div class="col-md-1">
    <%= link_to 'Back', store_path %>
</div>

app/views/products/show.html.erb
<% if notice %>
    <div class="alert alert-success" role="alert">
      <p id="notice"><%= notice %></p>
    </div>
<% end %>

<div class="page-header">
  <h1><%= @product.title %></h1>
</div>

<div class="row">
  <div class="col-md-2 image_product">
    <%= image_tag(@product.image_url, alt: @product.title, class: 'image') %>
  </div>
  <div class="col-md-8">
      <div class="panel panel-default">
        <div class="panel-heading">Description</div>
        <div class="panel-body">
          <%= @product.description %>
        </div>
      </div>
      <div class="col-md-2 price">Price: <span class="price-number"><%= number_to_currency @product.price %></span></div>
  </div>
</div>
<hr>

<div class="row">
  <div class="col-md-11"></div>
  <div class="col-md-1">
    <%= link_to 'Back', store_path %>
    <% if session[:user_id] %>
        |
        <%= link_to 'Edit', edit_product_path(@product)%>
    <% end %>
  </div>
</div>