config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'store#index', as: 'store'

  resources :products, except: :index
  resources :line_items, only: [:create, :destroy]
  resources :carts, only: [:show]
  resources :orders, except: [:edit, :update]

  # session
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy', as: :logout

end

app/controllers/store_controller.rb
class StoreController < ApplicationController

  skip_before_action :authorize

  def index
    @products = Product.order(:created_at).page params[:page]
    @user = User.find(session[:user_id]) if session[:user_id]
  end
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/store/index.html.erb
<% if @user %>
    <div class="greeting">
      <%= link_to 'Check orders', orders_path %>
      <br>
      <%= link_to 'Create new product', new_product_path %>
    </div>
<% end %>

<% if notice %>
    <div class="alert alert-success" role="alert">
      <p id="notice"><%= notice %></p>
    </div>
<% end %>
<div class="row">
<div class="page-header">
  <h1>Store</h1>
</div>
</div>
<div class="row">
    <% @products.each do |product| %>
        <div class="col-sm-3 col-md-3 col-lg-3">
          <div class="thumbnail product">
            <%= link_to (image_tag(product.image_url, alt: product.title, class: 'image')), product %>
            <div class="caption">
              <h3><%= product.title %></h3>
              <p class="description"><%= product.description.strip %></p>
              <p class="price"><%= number_to_currency product.price %></p>
              <%= button_to 'Add to cart', line_items_path(product_id: product), class: 'btn btn-success' %>
              <%= button_to 'Show more', product, method: :get, class: 'btn btn-info' %>
            </div>
          </div>
        </div>
    <% end %>
</div>
<div class="row">
  <div class="col-md-9"></div>
  <div class="col-md-3">
    <div class="pagination">
      <%= paginate @products %>
    </div>
  </div>
</div>