config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'store#index', as: 'store'

  resources :products, except: :index
  resources :line_items, only: [:create, :destroy]
  resources :carts, only: [:show]
  resources :orders, except: [:edit, :update]

  # session
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy', as: :logout

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Store</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top navbar_custom">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only"><a class="navbar-brand" href="<%= store_path %>">Depot</a></span>
      </button>
      <a class="navbar-brand navbar_titles" href="<%= store_path %>">Depot</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right navbar_right">
        <% unless session[:cart_id].nil? %>
            <li><a href="<%= cart_path session[:cart_id] %>" class="navbar_right_titles"><span class="glyphicon glyphicon-shopping-cart"></span> Cart <span class="badge navbar_titles badge_custom"><%= count_products %></span></a></li>
        <% end %>
        <% if session[:user_id].nil? %>
            <li class="login"><%= link_to 'Login', login_path, class: 'navbar_right_titles' %></li>
        <% else %>
            <li class="login"><%= link_to 'Logout', logout_path, method: :delete, class: 'navbar_right_titles' %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<%= yield %>

</body>
</html>